apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx
spec:
  nodeSelector:
    "kubernetes.io/os": linux
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
