apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: readOnlyPodsBinding
roleRef:
 kind: ClusterRole
 name: readOnly-Pods
 apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: "90938910-5484-4663-b257-e7714d47f9c5" # group id