apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: deleteBinding
 namespace: delete-access
roleRef:
 kind: Role
 name: deletePodsRole
 apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  apiGroup: rbac.authorization.k8s.io
  name: juan.osorio@microsoft.com #"<user e-mail address>"